stages:
  - quality
  - deploy

default:
  interruptible: true

image: gitlab.adeoweb.biz:8443/adeoweb/devops/magento-docker/magento-php:7.4-builder

quality:
  stage: quality
  before_script:
    - cp $AUTH /root/.composer/auth.json
    - chmod 400 /root/.composer/auth.json
  script:
    - make ci-composer-dev ci-check-style ci-unit-test

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG != null'
  before_script:
    - apk add --no-cache curl
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
